// Code generated by "stringer -type=FormOptionType -trimprefix=FormOption"; DO NOT EDIT.

package openconnect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormOptionText-1]
	_ = x[FormOptionPassword-2]
	_ = x[FormOptionSelect-3]
	_ = x[FormOptionHidden-4]
	_ = x[FormOptionToken-5]
	_ = x[FormOptionSSOToken-6]
	_ = x[FormOptionSSOUser-7]
}

const _FormOptionType_name = "TextPasswordSelectHiddenTokenSSOTokenSSOUser"

var _FormOptionType_index = [...]uint8{0, 4, 12, 18, 24, 29, 37, 44}

func (i FormOptionType) String() string {
	i -= 1
	if i < 0 || i >= FormOptionType(len(_FormOptionType_index)-1) {
		return "FormOptionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FormOptionType_name[_FormOptionType_index[i]:_FormOptionType_index[i+1]]
}
