// Code generated by "stringer -type=FormResult -trimprefix=FormResult"; DO NOT EDIT.

package openconnect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormResultErr - -1]
	_ = x[FormResultOk-0]
	_ = x[FormResultCancelled-1]
	_ = x[FormResultNewgroup-2]
}

const _FormResult_name = "ErrOkCancelledNewgroup"

var _FormResult_index = [...]uint8{0, 3, 5, 14, 22}

func (i FormResult) String() string {
	i -= -1
	if i < 0 || i >= FormResult(len(_FormResult_index)-1) {
		return "FormResult(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _FormResult_name[_FormResult_index[i]:_FormResult_index[i+1]]
}
