// Code generated by "stringer -type=LogLevel -trimprefix=LogLevel"; DO NOT EDIT.

package openconnect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelErr-0]
	_ = x[LogLevelInfo-1]
	_ = x[LogLevelDebug-2]
	_ = x[LogLevelTrace-3]
}

const _LogLevel_name = "ErrInfoDebugTrace"

var _LogLevel_index = [...]uint8{0, 3, 7, 12, 17}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
