// Code generated by "stringer -type=ConnectionState"; DO NOT EDIT.

package dialer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Offline-0]
	_ = x[Connecting-1]
	_ = x[Failed-2]
	_ = x[Online-3]
}

const _ConnectionState_name = "OfflineConnectingFailedOnline"

var _ConnectionState_index = [...]uint8{0, 7, 17, 23, 29}

func (i ConnectionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConnectionState_index)-1 {
		return "ConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionState_name[_ConnectionState_index[idx]:_ConnectionState_index[idx+1]]
}
