name: Build Nix Flakes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.gen-matrix.outputs.build }}
      release: ${{ steps.gen-matrix.outputs.release }}
      has_jobs: ${{ steps.gen-matrix.outputs.has_jobs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
      - name: Setup Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Get Build Matrix
        id: gen-matrix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/gen-matrix.sh > "$GITHUB_OUTPUT"

  build:
    needs: gen-matrix
    if: ${{ fromJson(needs.gen-matrix.outputs.has_jobs) }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.gen-matrix.outputs.build) }}
    runs-on: ${{ matrix.runner }}
    env:
      ARTIFACT_NAME: ${{ matrix.app }}-${{ matrix.system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
      - name: Setup Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build with Nix Flakes
        run: |
          nix build --show-trace -L .#${{ matrix.output }}
      - name: Package Release Asset
        run: |
          tar -czvf "${{ env.ARTIFACT_NAME }}.tgz" -C ./result .
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.tgz
          compression-level: 0

  release:
    needs:
      - gen-matrix
      - build
    if: ${{ fromJson(needs.gen-matrix.outputs.has_jobs) }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.gen-matrix.outputs.release) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
          merge-multiple: true
          pattern: ${{ matrix.app }}-*
      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ matrix.tag }}" \
            --repo "${{ github.repository }}" \
            --target "$GITHUB_SHA" \
            --title "${{ matrix.tag }}" \
            --notes "${{ matrix.changes }}" \
            artifacts/*

  bundle:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Bundle artifacts for GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./pages-content

          # Generate a simple index.html with a directory listing
          cat <<EOF > ./pages-content/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Pacman Builds</title>
          </head>
          <body>
            <h1>Pacman Builds</h1>
            <h2>Available Files</h2>
            <ul>
          EOF

          gh release list \
            --repo "${{ github.repository }}" \
            --json tagName --limit 25 \
          | jq -r '.[].tagName' \
          | while read -r TAG; do

          RELEASE_DATA=$(gh release view "$TAG" \
            --repo "${{ github.repository }}" \
            --json url,name,body)

          URL=$(jq -r '.url' <<< "$RELEASE_DATA")
          NAME=$(jq -r '.name' <<< "$RELEASE_DATA")
          BODY=$(jq -r '.body' <<< "$RELEASE_DATA")

          # Fallback to tag name if the release title is empty
          DISPLAY_NAME="${NAME:-$TAG}"

          cat <<EOF >> ./pages-content/index.html
              <li>
                <a href="$URL">$DISPLAY_NAME</a>
                <p>$BODY</p>
              </li>
          EOF
          done

          cat <<EOF >> ./pages-content/index.html
            </ul>
          </body>
          </html>
          EOF
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./pages-content

  deploy:
    needs: bundle
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
